1  ---
2
3  - name: Install Metricbeat on Webservers
4    hosts: webservers
5    become: true
6    tasks:
7
8  - name: Download Metricbeat
9    get_url:
10     url: https://artifacts.elastic.co/downloads/beats/metricbeat/metribeat-7.6.1-amd64.deb
11     dest: /etc
12
13 - name: Extract Metricbeat
14   command: dpkg -i /etc/metricbeat-7.6.1-amd64.deb
15
16 - name: Set metricbeat config file
17   copy:
18     src: /etc/ansible/files/configMetricbeatUnit13.yml
19     dest: /etc/metricbeat/metricbeat.yml
20     force: yes
21
22 - name: Enable metricbeat system module 
23   command: metricbeat modules enable docker
24
25 - name: Setup metricbeat
26   command: metricbeat setup
27
28 - name: Start metricbeat service
29   command: service metricbeat start
30
31 - name: Enable metric on boot
32   systemd:
33     name: metricbeat
34     enabled: yes
